### ISSUE TITLE
투표용 스테이징 검토하기

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/logo-summit#27]
최종 마감 시간:
7월 8일 수요일 오전 9시....

8시 30분쯤 출근해서 이전 준비 예정.

**Comment by mozodev** [comment]
라즈베리파이 우후
http://blog.kitematic.com/post/114866595734/connecting-kitematic-to-an-external-docker-engine

**Comment by mozodev** [comment]
@nanshil 많이 늦었지만 내일 저녁에라도 알려주시면 수정하겠습니다. 

- 국문 http://stage.logo.cckorea.org/ko
- 영문 http://stage.logo.cckorea.org/en

투표 취소는 전에도 설명드렸듯이 페이스북 방식으로 따로 버튼이 없습니다. 
좋아요 버튼 클릭하면 투표. 다시 클릭하면 취소 식으로 토글됩니다.

**Comment by nanshil** [comment]
텍스트부분은 확인했구요~

지금 투표 액션이 추천 손을 누르는건데...
직관적으로 괜찮은지, 아니면 손 배경에 "투표하기" 넣어서 버튼처럼 하는게 좋은지 의견 좀 부탁드릴께요~


참고 기획서:
https://drive.google.com/open?id=1sCmb-cKn98ZXYdsAxVPmmxQzDytyUrcFx3p32l6pKis

2015년 7월 7일 화요일, Yeongtaek Hong<notifications@github.com>님이 작성한 메시지:

**Comment by mozodev** [comment]
@khseo @soohyunpae 내일 오전 9시 공모 모드에서 투표 모드로 전환합니다. 관련해서 살펴보시고 오류나 수정할 사항 말씀해주세요~

**Comment by soohyunpae** [comment]
고생하셨습니다~!

국문사이트:
1. CC Global summit 2015 --> CC Global Summit 2015
제목과 본문 텍스트에 전부 s 가 소문자인데 대문자로 바꿔주세요~
2. 제목이 CC Global Summit 2015를 함께 할/로고에 투표해 주세요!
줄바꿈이 이렇게 되어야 가독성이 좋을 것 같은데...디자인이 어색해지면 할 수 없구요^^ (비전문가 의견)

영문사이트:
1. 첫째 문단에 날짜/장소 정보가 들어가 있어서요. 두번째 문장 수정 부탁드려요.
The Logo Contest for the CC Global Summit 2015 to be held in Seoul, Korea ran from June 8 through July 7 and submission is now closed. -->
The Logo Contest for the CC Global Summit 2015 ran from June 8 through July 7 and submission is now closed. 

2. CC Global Summit 2015 
Logo Contest - Open for Voting!
줄바꿈이 이렇게 되면 좋겠어요~! (역시 비전문가 의견)

**Comment by mozodev** [comment]
![en](https://cloud.githubusercontent.com/assets/1661950/8559622/d97057c2-2549-11e5-8b40-89f7d057e0b2.png)
![ko](https://cloud.githubusercontent.com/assets/1661950/8559623/d9719d44-2549-11e5-9c51-5efaec7f0054.png)
