### ISSUE TITLE
로고 공모 투표 및 심사 텍스트 

### ISSUE THREAD

**Issue by nanshil** [creativecommonskorea/logo-summit#28]
로고 공모 관련 투표 및 심사 진행 텍스트 정리했습니다.
@soohyunpae 님~ 영문 작업 부탁드려요~
@mozodev 님~ 8일부터심사 들어가야해서 저희가 테스트는 6일에 해야 할것 같아요(수정시간 확보를 위해) 6일(월) 오후에 페이지 테스트 해볼 수 있도록 진행 부탁드려요! 

https://docs.google.com/presentation/d/1sCmb-cKn98ZXYdsAxVPmmxQzDytyUrcFx3p32l6pKis/edit#slide=id.g5ac35ce34_0_87

**Comment by jenniferkang** [comment]
@nanshil  @mozodev  로고 공모 날짜 수정 부탁드려요. 
(영문버젼도 확인 부탁드려요 - 제가 확인을 해볼수가 없어서요..)

**Comment by nanshil** [comment]
저희가 관리 가능한 공모 등록 페이지는 적용 다 했구요!
게이트웨이 페이지는 맷한테 요청했는데.. @mozodev <https://github.com/mozodev>님~ 상단 이미지 수정
요청하면서 다시 한번 이야기해주세요~

2015년 7월 2일 오후 3:51, jenniferkang <notifications@github.com>님이 작성:

**Comment by mozodev** [comment]
@jenniferkang 
로고 공모 날짜는 수정했습니다. 아래 링크에서 국문 영문 확인할 수 있습니다.
http://logo.cckorea.org/ko
http://logo.cckorea.org/en

서밋 웹사이트 배너와 일정도 최종 반영됐습니다.
https://summit.creativecommons.org/kr/

**Comment by mozodev** [comment]
@soohyunpae 
구글 프레젠테이션 파일에 있는 문구들 영문 번역이 필요하겠습니다. 
급하지는 않고 다음주 월요일 중으로만 되면 일정에 차질이 없습니다.

## 투표
마일스톤 [vote](https://github.com/creativecommonskorea/logo-summit/milestones/vote)
```
#1 페이지
CC Global summit 2015를 함께 할 로고에 투표해주세요! 

한국에서 펼쳐질 CC Global summit 2015 로고 공모가
지난 6월 8일부터  7월 7일까지 진행되었습니다. 

접수된 아래 작품 중,
 CC Global summit 2015와 가장 잘 어울리는 로고에 투표해주세요!
(여러 작품 투표 가능, 한 작품에 중복 투표 불가)

온라인 투표와 심사 위원 평가를 거쳐 수상작은 7월 23일에 발표됩니다.    
```

## 심사
마일스톤 [final](https://github.com/creativecommonskorea/logo-summit/milestones/final)
저는 편의상 심사와 발표를 그냥 final로 합쳐서 마일스톤으로 만들었습니다.
```
CC Global summit 2015를 함께 할 로고를 심사중입니다. 

한국에서 펼쳐질 CC Global summit 2015 로고 공모가
지난 6월 8일부터 7월 7일까지 진행되었습니다. 

현재 심사위원 평가중입니다. 
최종 수상작은 7월 23일에 발표됩니다.    

```

## 최종 발표
마일스톤 [final](https://github.com/creativecommonskorea/logo-summit/milestones/final)
```
온라인 투표와 심사위원 평가를 거쳐 최종 선정작이 아래와 같이 선정되었습니다. 

최종 선정되신 OOO님께 축하드리며, 수상과 관련한 자세한 사항은 개별적으로 연락드리겠습니다. 

CC Global summit 2015에 관심을 가지고 참여해주신 모든분들께
진심으로 감사드립니다.

10월, 서울 국립중앙박물관에서 뵙겠습니다.  

```

**Comment by soohyunpae** [comment]
참고로 프레젠테이션 파일은 여깄습니다.ㅎ
https://docs.google.com/presentation/d/1xeCKWMspg1533JoFynMI1IBr7KUQXMTMOFYF-x9otGs/edit#slide=id.p

## 투표
마일스톤 [vote](https://github.com/creativecommonskorea/logo-summit/milestones/vote)
```
#1 페이지
CC Global Summit 2015 Logo Contest - Open for Voting!

The Logo Contest for the CC Global Summit 2015 to be held in Seoul, Korea ran from June 8 through July 7 and submission is now closed. 

Please help us pick the best logo design for the CC Global Summit 2015!
(You can vote on more than one design; your vote on a certain design counts only once.)

After the online public voting and judging by the CC Selection Committee, the winning logo will be announced on July 23.    


```

## 심사
마일스톤 [final](https://github.com/creativecommonskorea/logo-summit/milestones/final)
저는 편의상 심사와 발표를 그냥 final로 합쳐서 마일스톤으로 만들었습니다.
```
CC Global Summit 2015 Logo Contest - Judging Under Way!

The Logo Contest for the CC Global Summit 2015 to be held in Seoul, Korea ran from June 8 through July 7 and submission is now closed. 

The CC Selection Committee judging is now under way.
The winning logo will be announced on July 23, 2015.

```

## 최종 발표
마일스톤 [final](https://github.com/creativecommonskorea/logo-summit/milestones/final)
```
CC Global Summit 2015 Logo Contest - Winner Announced!

The Logo Contest for the CC Global Summit 2015 to be held in Seoul, Korea ran from June 8 through July 7 and submission is now closed. 


After online voting and CC Selection Committee judging, here we are pleased to announce the final winner.

Congratulations to OOO for winning the competition. 
The organizers will contact the winner via e-mail regarding the prize.

Thank you all who participated in the CC Global Summit 2015 Logo Contest.

Look forward to seeing you in Seoul this October!

```

**Comment by mozodev** [comment]
:+1:
