### ISSUE TITLE
온라인 투표 진행상황_15일 4시 기준 

### ISSUE THREAD

**Issue by nanshil** [creativecommonskorea/logo-summit#38]
15일 4시 기준 온라인 투표 진행 상황입니다.

- 네티즌 투표 1위와 슬로워크랑 선정한 3개중 1개가 겹치네요!(파란색 표기)
- 슬로워크에서 1순위로 한것은 현재 5위 안에 들지는 않아요! (노란색 표기)
- 투표수 차이가 많이 나지는 않아서 슬로워크에서 추천한 2개 (73,83)가 5위 안에 들수 있도록 모두 투표 해주시고 진행 상황 살피면 되겠죠?

@mozodev 님~ 저녁에 투표 상황 다시 한번만 체크해주세요~
@soohyunpae 님~ HQ랑 협의할 자료 이렇게 드리면 될지 알려주세요~
@khseo 슬로워크랑 논의한 것 중 1순위는 73번이고, 2순위를 83번으로 가도 될까요? 

NO	                           링크	                       투표수	      비고 
1	https://logo.cckorea.org/ko/node/83	192	         슬로워크 우선순위
2	https://logo.cckorea.org/ko/node/103	178	
3	https://logo.cckorea.org/ko/node/101	167	
4	https://logo.cckorea.org/ko/node/70	177	
5	https://logo.cckorea.org/ko/node/64	156	
-	https://logo.cckorea.org/ko/node/73	148	        슬로워크 우선순위 
-	https://logo.cckorea.org/ko/node/89	68	        슬로워크 우선순위

https://docs.google.com/spreadsheets/d/1Hr1fO4mD1xF1e16tf-0zvYvwcxDKYfrC7xmSfDYyk9c/edit?usp=sharing

**Comment by khseo** [comment]
@nanshil 네, 73번이 1순위였고 83번이 2순위였어요~ 저는 방금 73번에 투표했습니다ㅎ

**Comment by mozodev** [comment]
저녁 9시 기준 약간 변동이 있네요...
1,2,3 변동없음 4 신규진입 5 밀림...

1. https://logo.cckorea.org/ko/node/83 - 215 슬로워크 우선순위
2. https://logo.cckorea.org/ko/node/103 - 206
3. https://logo.cckorea.org/ko/node/101 - 194
4. https://logo.cckorea.org/ko/node/102 - 185 (막판 약진!)
5. https://logo.cckorea.org/ko/node/70 - 180(4번에 밀림)

**Comment by mozodev** [comment]
@creativecommonskorea/2015-summit 
투표 마감했고 심사 모드로 전환했는데 순위는 위와 같습니다.

1. https://logo.cckorea.org/ko/node/103 - 252 (2등에서 1등으로!) - 나머지 동일...
2. https://logo.cckorea.org/ko/node/83 - 240 슬로워크 우선순위
3. https://logo.cckorea.org/ko/node/101 - 240
4. https://logo.cckorea.org/ko/node/102 - 229 (막판 약진!)
5. https://logo.cckorea.org/ko/node/70 - 217 (4번에 밀림)

**Comment by soohyunpae** [comment]
음....일등이....일등이...

심사위원투표는 전에 제안한 건
CC Summit Steering Commitee (저랑 제니퍼님이 2주마다 회의하는 그룹으로 HQ스탭 중 써밋 관련 담당자들 그룹이에요) 랑 CC Program Committee (저랑 주영님이 들어가는 써밋 프로그램 프로포절 심사하는 그룹으로, HQ 스탭 몇과 각국 affiliate 대표들 열명 정도로 구성되어 있어요.) 의 투표로 하자고 얘기했었어요.
여기에 파이널 5개 주고 의견+투표 한 표씩 해달라고 할까 하는데 어떠신지요?
그냥 투표만 하면 결과를 예측하기 어려워질 수도 있지만 의견 달 수 있게 해놓고 우리 로컬팀 의견도 적극 피력하면 괜찮을 것 같아요.
