### ISSUE TITLE
최종 발표 모드로 전환 배포

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/logo-summit#41]
실서버에 적용하기

**Comment by mozodev** [comment]
적용하기 전에 슬로워크와 디자인안 수정에 대해 의견을 조율하고 있어서 아마도 오늘 중에는 배포 예정

**Comment by mozodev** [comment]
혹시 수정 사항 있으면 여기에 적어주시면 감사하겠습니다.

@soohyunpae 영문 적용 화면입니다.

![2015-07-24 11 58 35](https://cloud.githubusercontent.com/assets/1661950/8866804/90bd9e90-31fb-11e5-934a-aa01fc79ae05.png)

@nanshil 국문 적용 화면입니다.

![2015-07-24 11 58 54](https://cloud.githubusercontent.com/assets/1661950/8866808/9ecf6810-31fb-11e5-9379-92f3f24a02f3.png)

**Comment by soohyunpae** [comment]
영문 아래로 부탁드려요~

Thanks to everyone who entered our Logo Contest which ran from June 8 to July 7, 2015. 
After online public voting and Selection Committee's judging process, we are now very excited to announce the winner as below.

Congratulations to nareshagrawalart for winning the contest! 
The organizers will contact the winner via e-mail regarding the prize.

Thank you all who participated in the CC Global Summit 2015 Logo Contest again.

Look forward to seeing you in Seoul this October!


Logo Contest Winner

**Comment by mozodev** [comment]
@soohyunpae 
![2015-07-24 1 53 46](https://cloud.githubusercontent.com/assets/1661950/8867915/75157ee6-320b-11e5-94b6-152a7e3b8809.png)

**Comment by soohyunpae** [comment]
:+1:

**Comment by mozodev** [comment]
@creativecommonskorea/2015-summit 
최종 발표 모드 배포 완료~ 모두들 수고하셨습니다~
